export const START_GET_AGENTS = "START_GET_AGENTS";
export const ERROR_GET_AGENTS = "ERROR_GET_AGENTS";
export const SUCCESSFUL_GET_AGENTS = "SUCCESSFUL_GET_AGENTS";

export const START_GET_AGENT = "START_GET_AGENT";
export const ERROR_GET_AGENT = "ERROR_GET_AGENT";
export const SUCCESSFUL_GET_AGENT = "SUCCESSFUL_GET_AGENT";
